org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=384m -XX:ReservedCodeCacheSize=64m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false

org.gradle.workers.max=1
kotlin.daemon.jvmargs=-Xmx384m

kotlin.compiler.execution.strategy=in-process

# Avoid cross-drive incremental cache failures with the D: SDK/package cache.
kotlin.incremental=false
