-- Gemora Component 2 runtime schema compatibility patch
-- Safe to run repeatedly. No destructive DROP statements are used.

ALTER TABLE "Orders"
ADD COLUMN IF NOT EXISTS "FulfillmentStatus" character varying(50) NOT NULL DEFAULT 'Pending';

ALTER TABLE "Orders"
ADD COLUMN IF NOT EXISTS "HandedOverAt" timestamp with time zone NULL;

ALTER TABLE "Orders"
ADD COLUMN IF NOT EXISTS "DeliveredAt" timestamp with time zone NULL;

UPDATE "Orders"
SET "FulfillmentStatus" = 'Pending'
WHERE "FulfillmentStatus" IS NULL OR BTRIM("FulfillmentStatus") = '';

CREATE TABLE IF NOT EXISTS "OrderDeliveryDetails"
(
    "Id" uuid NOT NULL,
    "OrderId" uuid NOT NULL,
    "RecipientName" character varying(150) NOT NULL,
    "RecipientPhone" character varying(30) NOT NULL,
    "AlternatePhone" character varying(30),
    "AddressLine1" character varying(250) NOT NULL,
    "AddressLine2" character varying(250),
    "City" character varying(100) NOT NULL,
    "District" character varying(100) NOT NULL,
    "Region" character varying(100) NOT NULL,
    "PostalCode" character varying(20) NOT NULL,
    "CountryCode" character varying(2) NOT NULL,
    "NearestLandmark" character varying(250),
    "DeliveryInstructions" character varying(1000),
    "SignatureRequired" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NULL,
    "LastUpdatedByUserId" uuid NULL,
    "LockedAt" timestamp with time zone NULL,
    CONSTRAINT "PK_OrderDeliveryDetails" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrderDeliveryDetails_Orders_OrderId"
        FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_OrderDeliveryDetails_OrderId"
ON "OrderDeliveryDetails" ("OrderId");

CREATE TABLE IF NOT EXISTS "Shipments"
(
    "Id" uuid NOT NULL,
    "OrderId" uuid NOT NULL,
    "CourierName" character varying(150) NOT NULL,
    "TrackingNumber" character varying(150) NOT NULL,
    "TrackingUrl" character varying(1000),
    "ExpectedDeliveryDate" timestamp with time zone NULL,
    "DispatchNote" character varying(1000),
    "Status" character varying(50) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NULL,
    "HandedOverAt" timestamp with time zone NULL,
    "DeliveredAt" timestamp with time zone NULL,
    CONSTRAINT "PK_Shipments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Shipments_Orders_OrderId"
        FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Shipments_OrderId"
ON "Shipments" ("OrderId");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Shipments_TrackingNumber"
ON "Shipments" ("TrackingNumber");

CREATE TABLE IF NOT EXISTS "FulfillmentStatusHistories"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" uuid NOT NULL,
    "PreviousStatus" character varying(50),
    "NewStatus" character varying(50) NOT NULL,
    "ChangedByUserId" uuid NULL,
    "Note" character varying(1000),
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_FulfillmentStatusHistories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FulfillmentStatusHistories_Orders_OrderId"
        FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_FulfillmentStatusHistories_Users_ChangedByUserId"
        FOREIGN KEY ("ChangedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "IX_FulfillmentStatusHistories_OrderId"
ON "FulfillmentStatusHistories" ("OrderId");

CREATE INDEX IF NOT EXISTS "IX_FulfillmentStatusHistories_ChangedByUserId"
ON "FulfillmentStatusHistories" ("ChangedByUserId");

CREATE INDEX IF NOT EXISTS "IX_FulfillmentStatusHistories_CreatedAt"
ON "FulfillmentStatusHistories" ("CreatedAt");
