// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Gemora.Domain.Entities;
using Gemora.Domain.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Json;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion.Internal;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.Mapping;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Gemora.Infrastructure.Migrations.Optimized
{
    internal partial class InsuranceRecordEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Gemora.Domain.Entities.InsuranceRecord",
                typeof(InsuranceRecord),
                baseEntityType);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(InsuranceRecord).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InsuranceRecord).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.TypeMapping = GuidTypeMapping.Default.Clone(
                comparer: new ValueComparer<Guid>(
                    (Guid v1, Guid v2) => v1 == v2,
                    (Guid v) => v.GetHashCode(),
                    (Guid v) => v),
                keyComparer: new ValueComparer<Guid>(
                    (Guid v1, Guid v2) => v1 == v2,
                    (Guid v) => v.GetHashCode(),
                    (Guid v) => v),
                providerValueComparer: new ValueComparer<Guid>(
                    (Guid v1, Guid v2) => v1 == v2,
                    (Guid v) => v.GetHashCode(),
                    (Guid v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "uuid"));
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var coverageAmount = runtimeEntityType.AddProperty(
                "CoverageAmount",
                typeof(decimal),
                propertyInfo: typeof(InsuranceRecord).GetProperty("CoverageAmount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InsuranceRecord).GetField("<CoverageAmount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            coverageAmount.TypeMapping = NpgsqlDecimalTypeMapping.Default.Clone(
                comparer: new ValueComparer<decimal>(
                    (decimal v1, decimal v2) => v1 == v2,
                    (decimal v) => v.GetHashCode(),
                    (decimal v) => v),
                keyComparer: new ValueComparer<decimal>(
                    (decimal v1, decimal v2) => v1 == v2,
                    (decimal v) => v.GetHashCode(),
                    (decimal v) => v),
                providerValueComparer: new ValueComparer<decimal>(
                    (decimal v1, decimal v2) => v1 == v2,
                    (decimal v) => v.GetHashCode(),
                    (decimal v) => v));
            coverageAmount.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var coverageType = runtimeEntityType.AddProperty(
                "CoverageType",
                typeof(InsuranceCoverageType),
                propertyInfo: typeof(InsuranceRecord).GetProperty("CoverageType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(InsuranceRecord).GetField("<CoverageType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 50,
                providerPropertyType: typeof(string));
            coverageType.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
                comparer: new ValueComparer<InsuranceCoverageType>(
                    (InsuranceCoverageType v1, InsuranceCoverageType v2) => object.Equals((object)v1, (object)v2),
                    (InsuranceCoverageType v) => v.GetHashCode(),
                    (InsuranceCoverageType v) => v),
                keyComparer: new ValueComparer<InsuranceCoverageType>(
                    (InsuranceCoverageType v1, InsuranceCoverageType v2) => object.Equals((object)v1, (object)v2),
                    (InsuranceCoverageType v) => v.GetHashCode(),
                    (InsuranceCoverageType v) => v),
                providerValueComparer: new ValueComparer<string>(
                    (string v1, string v2) => v1 == v2,
                    (string v) => v.GetHashCode(),
                    (string v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "character varying(50)",
                    size: 50),
                converter: new ValueConverter<InsuranceCoverageType, string>(
                    (InsuranceCoverageType v) => v.ToString(),
                    (string v) => StringEnumConverter<InsuranceCoverageType, string, InsuranceCoverageType>.ConvertToEnum(v)),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<InsuranceCoverageType, string>(
                    JsonStringReaderWriter.Instance,
                    new ValueConverter<InsuranceCoverageType, string>(
                        (InsuranceCoverageType v) => v.ToString(),
                        (string v) => StringEnumConverter<InsuranceCoverageType, string, InsuranceCoverageType>.ConvertToEnum(v))));
            coverageType.TypeMapping = ((NpgsqlStringTypeMapping)coverageType.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
        coverageType.SetSentinelFromProviderValue("Standard");
        coverageType.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

        var createdAt = runtimeEntityType.AddProperty(
            "CreatedAt",
            typeof(DateTime),
            propertyInfo: typeof(InsuranceRecord).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(InsuranceRecord).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
        createdAt.TypeMapping = NpgsqlTimestampTzTypeMapping.Default.Clone(
            comparer: new ValueComparer<DateTime>(
                (DateTime v1, DateTime v2) => v1.Equals(v2),
                (DateTime v) => v.GetHashCode(),
                (DateTime v) => v),
            keyComparer: new ValueComparer<DateTime>(
                (DateTime v1, DateTime v2) => v1.Equals(v2),
                (DateTime v) => v.GetHashCode(),
                (DateTime v) => v),
            providerValueComparer: new ValueComparer<DateTime>(
                (DateTime v1, DateTime v2) => v1.Equals(v2),
                (DateTime v) => v.GetHashCode(),
                (DateTime v) => v));
        createdAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

        var currency = runtimeEntityType.AddProperty(
            "Currency",
            typeof(string),
            propertyInfo: typeof(InsuranceRecord).GetProperty("Currency", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            fieldInfo: typeof(InsuranceRecord).GetField("<Currency>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
            maxLength: 20);
        currency.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
            comparer: new ValueComparer<string>(
                (string v1, string v2) => v1 == v2,
                (string v) => v.GetHashCode(),
                (string v) => v),
            keyComparer: new ValueComparer<string>(
                (string v1, string v2) => v1 == v2,
                (string v) => v.GetHashCode(),
                (string v) => v),
            providerValueComparer: new ValueComparer<string>(
                (string v1, string v2) => v1 == v2,
                (string v) => v.GetHashCode(),
                (string v) => v),
            mappingInfo: new RelationalTypeMappingInfo(
                storeTypeName: "character varying(20)",
                size: 20));
        currency.TypeMapping = ((NpgsqlStringTypeMapping)currency.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
    currency.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

    var declaredValue = runtimeEntityType.AddProperty(
        "DeclaredValue",
        typeof(decimal),
        propertyInfo: typeof(InsuranceRecord).GetProperty("DeclaredValue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        fieldInfo: typeof(InsuranceRecord).GetField("<DeclaredValue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        sentinel: 0m);
    declaredValue.TypeMapping = NpgsqlDecimalTypeMapping.Default.Clone(
        comparer: new ValueComparer<decimal>(
            (decimal v1, decimal v2) => v1 == v2,
            (decimal v) => v.GetHashCode(),
            (decimal v) => v),
        keyComparer: new ValueComparer<decimal>(
            (decimal v1, decimal v2) => v1 == v2,
            (decimal v) => v.GetHashCode(),
            (decimal v) => v),
        providerValueComparer: new ValueComparer<decimal>(
            (decimal v1, decimal v2) => v1 == v2,
            (decimal v) => v.GetHashCode(),
            (decimal v) => v));
    declaredValue.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

    var policyReference = runtimeEntityType.AddProperty(
        "PolicyReference",
        typeof(string),
        propertyInfo: typeof(InsuranceRecord).GetProperty("PolicyReference", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        fieldInfo: typeof(InsuranceRecord).GetField("<PolicyReference>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        maxLength: 120);
    policyReference.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
        comparer: new ValueComparer<string>(
            (string v1, string v2) => v1 == v2,
            (string v) => v.GetHashCode(),
            (string v) => v),
        keyComparer: new ValueComparer<string>(
            (string v1, string v2) => v1 == v2,
            (string v) => v.GetHashCode(),
            (string v) => v),
        providerValueComparer: new ValueComparer<string>(
            (string v1, string v2) => v1 == v2,
            (string v) => v.GetHashCode(),
            (string v) => v),
        mappingInfo: new RelationalTypeMappingInfo(
            storeTypeName: "character varying(120)",
            size: 120));
    policyReference.TypeMapping = ((NpgsqlStringTypeMapping)policyReference.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
policyReference.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

var premiumAmount = runtimeEntityType.AddProperty(
    "PremiumAmount",
    typeof(decimal),
    propertyInfo: typeof(InsuranceRecord).GetProperty("PremiumAmount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    fieldInfo: typeof(InsuranceRecord).GetField("<PremiumAmount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    sentinel: 0m);
premiumAmount.TypeMapping = NpgsqlDecimalTypeMapping.Default.Clone(
    comparer: new ValueComparer<decimal>(
        (decimal v1, decimal v2) => v1 == v2,
        (decimal v) => v.GetHashCode(),
        (decimal v) => v),
    keyComparer: new ValueComparer<decimal>(
        (decimal v1, decimal v2) => v1 == v2,
        (decimal v) => v.GetHashCode(),
        (decimal v) => v),
    providerValueComparer: new ValueComparer<decimal>(
        (decimal v1, decimal v2) => v1 == v2,
        (decimal v) => v.GetHashCode(),
        (decimal v) => v));
premiumAmount.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

var provider = runtimeEntityType.AddProperty(
    "Provider",
    typeof(string),
    propertyInfo: typeof(InsuranceRecord).GetProperty("Provider", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    fieldInfo: typeof(InsuranceRecord).GetField("<Provider>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    maxLength: 100);
provider.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
    comparer: new ValueComparer<string>(
        (string v1, string v2) => v1 == v2,
        (string v) => v.GetHashCode(),
        (string v) => v),
    keyComparer: new ValueComparer<string>(
        (string v1, string v2) => v1 == v2,
        (string v) => v.GetHashCode(),
        (string v) => v),
    providerValueComparer: new ValueComparer<string>(
        (string v1, string v2) => v1 == v2,
        (string v) => v.GetHashCode(),
        (string v) => v),
    mappingInfo: new RelationalTypeMappingInfo(
        storeTypeName: "character varying(100)",
        size: 100));
provider.TypeMapping = ((NpgsqlStringTypeMapping)provider.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
provider.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

var shipmentId = runtimeEntityType.AddProperty(
    "ShipmentId",
    typeof(Guid),
    propertyInfo: typeof(InsuranceRecord).GetProperty("ShipmentId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    fieldInfo: typeof(InsuranceRecord).GetField("<ShipmentId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
shipmentId.TypeMapping = GuidTypeMapping.Default.Clone(
    comparer: new ValueComparer<Guid>(
        (Guid v1, Guid v2) => v1 == v2,
        (Guid v) => v.GetHashCode(),
        (Guid v) => v),
    keyComparer: new ValueComparer<Guid>(
        (Guid v1, Guid v2) => v1 == v2,
        (Guid v) => v.GetHashCode(),
        (Guid v) => v),
    providerValueComparer: new ValueComparer<Guid>(
        (Guid v1, Guid v2) => v1 == v2,
        (Guid v) => v.GetHashCode(),
        (Guid v) => v),
    mappingInfo: new RelationalTypeMappingInfo(
        storeTypeName: "uuid"));
shipmentId.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

var status = runtimeEntityType.AddProperty(
    "Status",
    typeof(InsuranceStatus),
    propertyInfo: typeof(InsuranceRecord).GetProperty("Status", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    fieldInfo: typeof(InsuranceRecord).GetField("<Status>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    maxLength: 50,
    providerPropertyType: typeof(string));
status.TypeMapping = NpgsqlStringTypeMapping.Default.Clone(
    comparer: new ValueComparer<InsuranceStatus>(
        (InsuranceStatus v1, InsuranceStatus v2) => object.Equals((object)v1, (object)v2),
        (InsuranceStatus v) => v.GetHashCode(),
        (InsuranceStatus v) => v),
    keyComparer: new ValueComparer<InsuranceStatus>(
        (InsuranceStatus v1, InsuranceStatus v2) => object.Equals((object)v1, (object)v2),
        (InsuranceStatus v) => v.GetHashCode(),
        (InsuranceStatus v) => v),
    providerValueComparer: new ValueComparer<string>(
        (string v1, string v2) => v1 == v2,
        (string v) => v.GetHashCode(),
        (string v) => v),
    mappingInfo: new RelationalTypeMappingInfo(
        storeTypeName: "character varying(50)",
        size: 50),
    converter: new ValueConverter<InsuranceStatus, string>(
        (InsuranceStatus v) => v.ToString(),
        (string v) => StringEnumConverter<InsuranceStatus, string, InsuranceStatus>.ConvertToEnum(v)),
    jsonValueReaderWriter: new JsonConvertedValueReaderWriter<InsuranceStatus, string>(
        JsonStringReaderWriter.Instance,
        new ValueConverter<InsuranceStatus, string>(
            (InsuranceStatus v) => v.ToString(),
            (string v) => StringEnumConverter<InsuranceStatus, string, InsuranceStatus>.ConvertToEnum(v))));
status.TypeMapping = ((NpgsqlStringTypeMapping)status.TypeMapping).Clone(npgsqlDbType: NpgsqlTypes.NpgsqlDbType.Varchar);
status.SetSentinelFromProviderValue("Active");
status.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

var updatedAt = runtimeEntityType.AddProperty(
    "UpdatedAt",
    typeof(DateTime),
    propertyInfo: typeof(InsuranceRecord).GetProperty("UpdatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    fieldInfo: typeof(InsuranceRecord).GetField("<UpdatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
    sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
updatedAt.TypeMapping = NpgsqlTimestampTzTypeMapping.Default.Clone(
    comparer: new ValueComparer<DateTime>(
        (DateTime v1, DateTime v2) => v1.Equals(v2),
        (DateTime v) => v.GetHashCode(),
        (DateTime v) => v),
    keyComparer: new ValueComparer<DateTime>(
        (DateTime v1, DateTime v2) => v1.Equals(v2),
        (DateTime v) => v.GetHashCode(),
        (DateTime v) => v),
    providerValueComparer: new ValueComparer<DateTime>(
        (DateTime v1, DateTime v2) => v1.Equals(v2),
        (DateTime v) => v.GetHashCode(),
        (DateTime v) => v));
updatedAt.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

var key = runtimeEntityType.AddKey(
    new[] { id });
runtimeEntityType.SetPrimaryKey(key);

var index = runtimeEntityType.AddIndex(
    new[] { policyReference },
    unique: true);

var index0 = runtimeEntityType.AddIndex(
    new[] { shipmentId });

return runtimeEntityType;
}

public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
{
    var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("ShipmentId") },
        principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
        principalEntityType,
        deleteBehavior: DeleteBehavior.Cascade,
        required: true);

    var shipment = declaringEntityType.AddNavigation("Shipment",
        runtimeForeignKey,
        onDependent: true,
        typeof(Shipment),
        propertyInfo: typeof(InsuranceRecord).GetProperty("Shipment", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        fieldInfo: typeof(InsuranceRecord).GetField("<Shipment>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

    var insuranceRecords = principalEntityType.AddNavigation("InsuranceRecords",
        runtimeForeignKey,
        onDependent: false,
        typeof(ICollection<InsuranceRecord>),
        propertyInfo: typeof(Shipment).GetProperty("InsuranceRecords", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
        fieldInfo: typeof(Shipment).GetField("<InsuranceRecords>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

    return runtimeForeignKey;
}

public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
{
    runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
    runtimeEntityType.AddAnnotation("Relational:Schema", null);
    runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
    runtimeEntityType.AddAnnotation("Relational:TableName", "InsuranceRecords");
    runtimeEntityType.AddAnnotation("Relational:ViewName", null);
    runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

    Customize(runtimeEntityType);
}

static partial void Customize(RuntimeEntityType runtimeEntityType);
}
}
