
using System.Net;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace Gemora.Infrastructure.Services;

public sealed class SupabaseStorageClient
{
    private readonly HttpClient _httpClient;

    private readonly string _projectUrl;

    private readonly string _secretKey;

    // ============================================================
    // STORAGE BUCKETS
    // ============================================================

    private const string GemImagesBucket = "gem-images";

    private const string ProfileImagesBucket = "profile-images";

    private const string CertificatesBucket = "gem-certificates";

    // Private certificates must NOT use public URLs.

    private const string PrivateCertificatePrefix =
        "supabase-private://gem-certificates/";

    // Object names are generated by our backend.
    // Folder separators and arbitrary paths are not accepted.

    private static readonly Regex SafeObjectName = new(
        @"^[A-Za-z0-9_-]+\.(jpg|jpeg|png|webp|pdf)$",
        RegexOptions.Compiled |
        RegexOptions.IgnoreCase
    );

    // ============================================================
    // CONSTRUCTOR
    // ============================================================

    public SupabaseStorageClient(
        HttpClient httpClient,
        SupabaseStorageOptions options)
    {
        if (options == null)
        {
            throw new ArgumentNullException(nameof(options));
        }

        if (string.IsNullOrWhiteSpace(options.ProjectUrl))
        {
            throw new InvalidOperationException(
                "Supabase Storage project URL is missing."
            );
        }

        if (string.IsNullOrWhiteSpace(options.ServiceRoleKey))
        {
            throw new InvalidOperationException(
                "Supabase Storage secret API key is missing."
            );
        }

        _projectUrl = options.ProjectUrl.TrimEnd('/');

        _secretKey = options.ServiceRoleKey.Trim();

        // This implementation uses the NEW Supabase secret key.

        if (!_secretKey.StartsWith(
                "sb_secret_",
                StringComparison.Ordinal))
        {
            throw new InvalidOperationException(
                "Please configure a Supabase Secret API Key beginning with sb_secret_."
            );
        }

        if (
            !Uri.TryCreate(
                _projectUrl,
                UriKind.Absolute,
                out var projectUri
            ) ||
            projectUri.Scheme != Uri.UriSchemeHttps ||
            !string.IsNullOrEmpty(projectUri.UserInfo) ||
            !string.IsNullOrEmpty(projectUri.Query) ||
            !string.IsNullOrEmpty(projectUri.Fragment) ||
            !string.IsNullOrEmpty(projectUri.AbsolutePath.Trim('/')) ||
            !projectUri.Host.EndsWith(
                ".supabase.co",
                StringComparison.OrdinalIgnoreCase)
        )
        {
            throw new InvalidOperationException(
                "Supabase Storage requires a valid HTTPS Supabase project URL."
            );
        }

        _httpClient = httpClient;

        _httpClient.BaseAddress = new Uri(
            $"{_projectUrl}/storage/v1/"
        );

        _httpClient.Timeout =
            TimeSpan.FromSeconds(90);
    }

    // ============================================================
    // CREATE AUTHENTICATED SUPABASE REQUEST
    //
    // Modern sb_secret_ keys are NOT JWT tokens.
    //
    // IMPORTANT:
    // Use the apikey header only.
    // Do not add Authorization: Bearer sb_secret_...
    // ============================================================

    private HttpRequestMessage CreateRequest(
        HttpMethod method,
        string relativePath)
    {
        var request = new HttpRequestMessage(
            method,
            relativePath
        );

        request.Headers.Add(
            "apikey",
            _secretKey
        );

        return request;
    }

    // ============================================================
    // VALIDATE BUCKET AND OBJECT NAME
    // ============================================================

    private static void ValidateObject(
        string bucket,
        string objectName)
    {
        var allowedBucket =
            bucket == GemImagesBucket ||
            bucket == ProfileImagesBucket ||
            bucket == CertificatesBucket;

        if (!allowedBucket)
        {
            throw new InvalidOperationException(
                "The requested storage bucket is not allowed."
            );
        }

        if (
            string.IsNullOrWhiteSpace(objectName) ||
            !SafeObjectName.IsMatch(objectName)
        )
        {
            throw new InvalidOperationException(
                "The storage filename is invalid."
            );
        }
    }

    // ============================================================
    // VALIDATE FILE FORMAT
    // ============================================================

    private static void ValidateFileType(
        string bucket,
        string objectName,
        string contentType)
    {
        var extension = Path.GetExtension(
            objectName
        ).ToLowerInvariant();

        var expectedContentType = extension switch
        {
            ".jpg" or ".jpeg" => "image/jpeg",

            ".png" => "image/png",

            ".webp" => "image/webp",

            ".pdf" => "application/pdf",

            _ => null
        };

        if (
            expectedContentType == null ||
            !string.Equals(
                contentType,
                expectedContentType,
                StringComparison.OrdinalIgnoreCase
            )
        )
        {
            throw new InvalidOperationException(
                "The uploaded file type does not match its extension."
            );
        }

        // Public image buckets only support images.

        if (
            bucket == GemImagesBucket ||
            bucket == ProfileImagesBucket
        )
        {
            if (
                extension != ".jpg" &&
                extension != ".jpeg" &&
                extension != ".png" &&
                extension != ".webp"
            )
            {
                throw new InvalidOperationException(
                    "Only JPG, PNG and WEBP images are allowed."
                );
            }
        }

        // The private certificate bucket accepts PDF/JPG/PNG.

        if (bucket == CertificatesBucket)
        {
            if (
                extension != ".pdf" &&
                extension != ".jpg" &&
                extension != ".jpeg" &&
                extension != ".png"
            )
            {
                throw new InvalidOperationException(
                    "Certificates must be PDF, JPG or PNG files."
                );
            }
        }
    }

    // ============================================================
    // UPLOAD FILE TO SUPABASE STORAGE
    //
    // Public images return:
    //
    // https://PROJECT.supabase.co/storage/v1/object/public/...
    //
    // Private certificates return:
    //
    // supabase-private://gem-certificates/FILENAME
    //
    // The private reference is stored in PostgreSQL.
    // A signed URL is generated separately when required.
    // ============================================================

    public async Task<string> UploadAsync(
        string bucket,
        string objectName,
        Stream source,
        string contentType,
        long maximumBytes,
        CancellationToken cancellationToken = default)
    {
        ValidateObject(
            bucket,
            objectName
        );

        ValidateFileType(
            bucket,
            objectName,
            contentType
        );

        if (source == null || !source.CanRead)
        {
            throw new InvalidOperationException(
                "The uploaded file cannot be read."
            );
        }

        if (maximumBytes <= 0)
        {
            throw new InvalidOperationException(
                "The maximum upload size is invalid."
            );
        }

        // ========================================================
        // BUCKET-SPECIFIC MAXIMUM SIZES
        //
        // Public images: 5 MB
        // Certificates: 10 MB
        // ========================================================

        long bucketMaximumBytes =
            bucket == CertificatesBucket
                ? 10L * 1024 * 1024
                : 5L * 1024 * 1024;

        var allowedBytes = Math.Min(
            maximumBytes,
            bucketMaximumBytes
        );

        // ========================================================
        // READ THE FILE WITH A STRICT SIZE LIMIT
        // ========================================================

        using var buffer = new MemoryStream();

        var chunk = new byte[81920];

        long totalBytes = 0;

        int bytesRead;

        while (
            (bytesRead = await source.ReadAsync(
                chunk.AsMemory(),
                cancellationToken
            )) > 0
        )
        {
            totalBytes += bytesRead;

            if (totalBytes > allowedBytes)
            {
                throw new InvalidOperationException(
                    "The selected file exceeds the allowed upload size."
                );
            }

            await buffer.WriteAsync(
                chunk.AsMemory(0, bytesRead),
                cancellationToken
            );
        }

        if (totalBytes == 0)
        {
            throw new InvalidOperationException(
                "The selected file is empty."
            );
        }

        // ========================================================
        // BUILD SUPABASE UPLOAD REQUEST
        // ========================================================

        var encodedObjectName =
            Uri.EscapeDataString(objectName);

        using var request = CreateRequest(
            HttpMethod.Post,
            $"object/{bucket}/{encodedObjectName}"
        );

        // Prevent overwriting an existing object.

        request.Headers.TryAddWithoutValidation(
            "x-upsert",
            "false"
        );

        request.Content =
            new ByteArrayContent(buffer.ToArray());

        request.Content.Headers.ContentType =
            new MediaTypeHeaderValue(contentType);

        // ========================================================
        // SEND FILE TO SUPABASE
        // ========================================================

        using var response =
            await _httpClient.SendAsync(
                request,
                cancellationToken
            );

        if (!response.IsSuccessStatusCode)
        {
            throw new InvalidOperationException(
                $"Supabase Storage upload failed. HTTP {(int)response.StatusCode}."
            );
        }

        // ========================================================
        // RETURN PRIVATE CERTIFICATE REFERENCE
        // ========================================================

        if (bucket == CertificatesBucket)
        {
            return
                $"{PrivateCertificatePrefix}{objectName}";
        }

        // ========================================================
        // RETURN PUBLIC IMAGE URL
        // ========================================================

        return
            $"{_projectUrl}/storage/v1/object/public/{bucket}/{encodedObjectName}";
    }

    // ============================================================
    // PARSE A STORED SUPABASE FILE REFERENCE
    //
    // Supports:
    //
    // 1. Public URLs from THIS Supabase project.
    //
    // 2. Our private gem certificate reference format.
    //
    // Rejects:
    //
    // - Other websites
    // - Arbitrary file paths
    // - Legacy /uploads/... URLs
    // - Unknown buckets
    // ============================================================

    private bool TryParseReference(
        string? reference,
        out string bucket,
        out string objectName)
    {
        bucket = "";

        objectName = "";

        if (string.IsNullOrWhiteSpace(reference))
        {
            return false;
        }

        // ========================================================
        // PRIVATE CERTIFICATE
        // ========================================================

        if (
            reference.StartsWith(
                PrivateCertificatePrefix,
                StringComparison.Ordinal
            )
        )
        {
            bucket = CertificatesBucket;

            objectName = reference.Substring(
                PrivateCertificatePrefix.Length
            );
        }
        else
        {
            // ====================================================
            // PUBLIC IMAGE URL
            // ====================================================

            var publicPrefix =
                $"{_projectUrl}/storage/v1/object/public/";

            if (
                !reference.StartsWith(
                    publicPrefix,
                    StringComparison.OrdinalIgnoreCase
                )
            )
            {
                return false;
            }

            var remaining = reference.Substring(
                publicPrefix.Length
            );

            var separatorIndex =
                remaining.IndexOf('/');

            if (separatorIndex <= 0)
            {
                return false;
            }

            bucket = remaining.Substring(
                0,
                separatorIndex
            );

            objectName = Uri.UnescapeDataString(
                remaining.Substring(separatorIndex + 1)
            );

            // Only public buckets can use public references.

            if (
                bucket != GemImagesBucket &&
                bucket != ProfileImagesBucket
            )
            {
                return false;
            }
        }

        // Reject folder traversal and unexpected filenames.

        if (!SafeObjectName.IsMatch(objectName))
        {
            return false;
        }

        return true;
    }

    // ============================================================
    // DELETE FILE FROM SUPABASE
    //
    // Old local /uploads/... URLs are intentionally ignored.
    //
    // This prevents accidentally sending unrelated URLs
    // to the Supabase Storage deletion API.
    // ============================================================

    public async Task DeleteAsync(
        string? reference,
        CancellationToken cancellationToken = default)
    {
        if (
            !TryParseReference(
                reference,
                out var bucket,
                out var objectName
            )
        )
        {
            return;
        }

        var encodedObjectName =
            Uri.EscapeDataString(objectName);

        using var request = CreateRequest(
            HttpMethod.Delete,
            $"object/{bucket}/{encodedObjectName}"
        );

        using var response =
            await _httpClient.SendAsync(
                request,
                cancellationToken
            );

        // An already-deleted object does not need cleanup again.

        if (response.StatusCode == HttpStatusCode.NotFound)
        {
            return;
        }

        response.EnsureSuccessStatusCode();
    }

    // ============================================================
    // DOWNLOAD GEMSTONE IMAGE FOR THE AI AGENT
    //
    // Only images from our own gem-images bucket
    // can be downloaded through this method.
    //
    // This prevents fetching an arbitrary external URL.
    // ============================================================

    public async Task<byte[]?> DownloadGemImageAsync(
        string? imageReference,
        CancellationToken cancellationToken = default)
    {
        if (
            !TryParseReference(
                imageReference,
                out var bucket,
                out var objectName
            ) ||
            bucket != GemImagesBucket
        )
        {
            return null;
        }

        var encodedObjectName =
            Uri.EscapeDataString(objectName);

        using var request = CreateRequest(
            HttpMethod.Get,
            $"object/public/{GemImagesBucket}/{encodedObjectName}"
        );

        using var response =
            await _httpClient.SendAsync(
                request,
                HttpCompletionOption.ResponseHeadersRead,
                cancellationToken
            );

        if (response.StatusCode == HttpStatusCode.NotFound)
        {
            return null;
        }

        response.EnsureSuccessStatusCode();

        // ========================================================
        // LIMIT THE AI IMAGE SIZE TO 5 MB
        // ========================================================

        const long maxBytes =
            5L * 1024 * 1024;

        await using var source =
            await response.Content.ReadAsStreamAsync(
                cancellationToken
            );

        using var buffer = new MemoryStream();

        var chunk = new byte[81920];

        long totalBytes = 0;

        int bytesRead;

        while (
            (bytesRead = await source.ReadAsync(
                chunk.AsMemory(),
                cancellationToken
            )) > 0
        )
        {
            totalBytes += bytesRead;

            if (totalBytes > maxBytes)
            {
                throw new InvalidOperationException(
                    "The gemstone evidence exceeds the supported AI image size."
                );
            }

            await buffer.WriteAsync(
                chunk.AsMemory(0, bytesRead),
                cancellationToken
            );
        }

        if (totalBytes == 0)
        {
            return null;
        }

        return buffer.ToArray();
    }

    // ============================================================
    // CREATE SIGNED URL FOR PRIVATE GEM CERTIFICATE
    //
    // IMPORTANT SECURITY RULE:
    //
    // This method must only be called by an API controller
    // AFTER checking that the authenticated user is permitted
    // to view the requested listing's certificate.
    //
    // It must not be exposed as an unrestricted public endpoint.
    // ============================================================

    public async Task<string> CreateCertificateSignedUrlAsync(
        string? certificateReference,
        CancellationToken cancellationToken = default)
    {
        if (
            !TryParseReference(
                certificateReference,
                out var bucket,
                out var objectName
            ) ||
            bucket != CertificatesBucket
        )
        {
            throw new InvalidOperationException(
                "This certificate is not stored in the private Supabase bucket."
            );
        }

        var encodedObjectName =
            Uri.EscapeDataString(objectName);

        // ========================================================
        // REQUEST SIGNED URL
        // ========================================================

        using var request = CreateRequest(
            HttpMethod.Post,
            $"object/sign/{CertificatesBucket}/{encodedObjectName}"
        );

        // URL expires after 60 seconds.

        request.Content = JsonContent.Create(
            new
            {
                expiresIn = 60
            }
        );

        using var response =
            await _httpClient.SendAsync(
                request,
                cancellationToken
            );

        response.EnsureSuccessStatusCode();

        // ========================================================
        // READ SUPABASE RESPONSE
        // ========================================================

        await using var responseStream =
            await response.Content.ReadAsStreamAsync(
                cancellationToken
            );

        using var json =
            await JsonDocument.ParseAsync(
                responseStream,
                cancellationToken: cancellationToken
            );

        if (
            !json.RootElement.TryGetProperty(
                "signedURL",
                out var signedUrlElement
            )
        )
        {
            throw new InvalidOperationException(
                "Supabase did not return a certificate access link."
            );
        }

        var signedUrl =
            signedUrlElement.GetString();

        if (string.IsNullOrWhiteSpace(signedUrl))
        {
            throw new InvalidOperationException(
                "The generated certificate link is empty."
            );
        }

        // ========================================================
        // HANDLE SUPABASE RELATIVE SIGNED URL
        //
        // Example:
        // /object/sign/gem-certificates/file.pdf?token=...
        // ========================================================

        if (
            signedUrl.StartsWith(
                $"/object/sign/{CertificatesBucket}/",
                StringComparison.Ordinal
            )
        )
        {
            return
                $"{_projectUrl}/storage/v1{signedUrl}";
        }

        // Some responses may already include /storage/v1.

        if (
            signedUrl.StartsWith(
                $"/storage/v1/object/sign/{CertificatesBucket}/",
                StringComparison.Ordinal
            )
        )
        {
            return $"{_projectUrl}{signedUrl}";
        }

        // ========================================================
        // HANDLE ABSOLUTE URL
        //
        // Accept only a signed URL belonging to our own
        // Supabase project's certificate bucket.
        // ========================================================

        var expectedPrefix =
            $"{_projectUrl}/storage/v1/object/sign/{CertificatesBucket}/";

        if (
            !signedUrl.StartsWith(
                expectedPrefix,
                StringComparison.Ordinal
            )
        )
        {
            throw new InvalidOperationException(
                "Supabase returned an unexpected certificate URL."
            );
        }

        return signedUrl;
    }
}
